---
firewall_default_input_policy: DROP
firewall_default_forward_policy: ACCEPT
firewall_default_output_policy: ACCEPT

firewall_default_sources: "{{ local_networks }}"

firewall_services:

  ssh:
    enabled: true
    protocol: tcp
    ports:
      - 22
    sources:
      - 192.168.0.100/32

  nginx:
    enabled: true
    protocol: tcp
    ports:
      - 80
      - 443
      - 8000

  dns-udp:
    enabled: true
    protocol: udp
    ports:
      - 53

  dns-tcp:
    enabled: true
    protocol: tcp
    ports:
      - 53

  etcd:
    enabled: true
    protocol: tcp
    ports:
      - 2379
    sources:
      - 192.168.0.0/24

  patroni:
    enabled: true
    protocol: tcp
    ports:
      - 8008
    sources:
      - 192.168.0.0/24

  postgres:
    enabled: true
    protocol: tcp
    ports:
      - 5432
    sources:
      - 192.168.0.0/24

  docker-flask:
    enabled: true
    protocol: tcp
    ports:
      - 5000
      - 8080

  gitlab-http:
    enabled: true
    protocol: tcp
    ports:
      - 80

  gitlab-https:
    enabled: true
    protocol: tcp
    ports:
      - 443

  gitlab-ssh:
    enabled: true
    protocol: tcp
    ports:
      - 22

  harbor:
    enabled: true
    protocol: tcp
    ports:
      - 8080
      - 8443
      - 8081

  k3s-api:
    enabled: true
    protocol: tcp
    ports:
      - 6443
    sources:
      - 192.168.0.0/24

  k3s-supervisor:
    enabled: true
    protocol: tcp
    ports:
      - 9345
    sources:
      - 192.168.0.0/24

  kubelet:
    enabled: true
    protocol: tcp
    ports:
      - 10250
    sources:
      - 192.168.0.0/24

  nodeport:
    enabled: true
    protocol: tcp
    ports:
      - 30000
      - 32767
