---
firewall_default_input_policy: DROP
firewall_default_forward_policy: ACCEPT
firewall_default_output_policy: ACCEPT

firewall_default_sources: "{{ local_networks }}"

firewall_services:

  ssh:
    enabled: true
    protocol: tcp
    ports:
      - 22
    sources:
      - 192.168.0.100/32

  icmp:
    enabled: true
    protocol: icmp

  nginx:
    enabled: true
    protocol: tcp
    ports:
      - 80
      - 443
      - 8000

  dns-udp:
    enabled: true
    protocol: udp
    ports:
      - 53

  dns-tcp:
    enabled: true
    protocol: tcp
    ports:
      - 53

  etcd:
    enabled: true
    protocol: tcp
    ports:
      - 2379

  patroni:
    enabled: true
    protocol: tcp
    ports:
      - 8008

  postgres:
    enabled: true
    protocol: tcp
    ports:
      - 5432

  docker-flask:
    enabled: true
    protocol: tcp
    ports:
      - 5000
      - 8080

  harbor:
    enabled: true
    protocol: tcp
    ports:
      - 8080
      - 8443
      - 8081

  k3s-api:
    enabled: true
    protocol: tcp
    ports:
      - 6443

  k3s-supervisor:
    enabled: true
    protocol: tcp
    ports:
      - 9345

  dns-ca-k3s:
    enabled: true
    protocol: tcp
    ports:
      - 9000
    sources:
      - 192.168.0.0/24

  kubelet:
    enabled: true
    protocol: tcp
    ports:
      - 10250

  flannel:
    enabled: true
    protocol: udp
    ports:
      - 8472

  nodeport:
    enabled: true
    protocol: tcp
    ports:
      - 30000
      - 32767
