---
- name: Include repository tasks
  ansible.builtin.import_tasks: repository.yml


- name: Include etcd installation tasks
  ansible.builtin.import_tasks: install_etcd.yml


- name: Include Patroni installation tasks
  ansible.builtin.import_tasks: install_patroni.yml


- name: Include Patroni configuration tasks
  ansible.builtin.import_tasks: configure.yml


- name: Include Patroni service tasks
  ansible.builtin.import_tasks: service.yml


- name: Include verification tasks
  ansible.builtin.import_tasks: verify.yml
