---
galaxy_info:
  author: DiegoGarsia
  description: Install and configure PostgreSQL server
  license: MIT

  min_ansible_version: "2.16"

  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
