[proxmox_host]
proxmox ansible_host=192.168.0.200

[jump_host]
jumphost ansible_host=192.168.0.100

[lxc]
nginx ansible_host=192.168.0.101
docker ansible_host=192.168.0.102
dns ansible_host=192.168.0.103

[kvm]
centos ansible_host=192.168.0.150
pg-node-01 ansible_host=192.168.0.151
pg-node-02 ansible_host=192.168.0.152
pg-node-03 ansible_host=192.168.0.153
gitlab ansible_host=192.168.0.154
master ansible_host=192.168.0.155
worker ansible_host=192.168.0.156

[lxc_proxy]
proxy-docker ansible_host=192.168.0.101

[kvm_proxy]
proxy-centos ansible_host=192.168.0.101

[dns_host]
dns

[dns_records:children]
proxmox_host
jump_host
lxc
kvm

[nginx_host]
nginx

[backend]
docker
centos 

[postgres]
pg-node-01
pg-node-02
pg-node-03

[patroni]
pg-node-02
pg-node-03

[etcd]
pg-node-01

[gitlab_hosts]
gitlab

[kubernetes_master]
master

[kubernetes_workers]
worker

[kubernetes:children]
kubernetes_master
kubernetes_workers

[managed:children]
lxc
kvm

[os_ubuntu]
jumphost
nginx
docker
dns
pg-node-01
pg-node-02
pg-node-03
gitlab
master
worker

[os_centos]
centos

[docker_hosts]
docker
