[proxmox_host]
proxmox ansible_host=192.168.0.200

[jump_host]
jumphost ansible_host=192.168.0.100

[lxc]
dns ansible_host=192.168.0.103
test-ansible-ubuntu ansible_host=192.168.0.110

[kvm]
kubernetes ansible_host=192.168.0.160
gitlab-clarity ansible_host=192.168.0.161

[ubuntu_hosts]
test-ansible-ubuntu
