galaxy_info:
  author: Diego Garcia
  description: Ansible role for deploying Patroni PostgreSQL HA cluster
  company: ""
  license: MIT
  min_ansible_version: "2.16"

  platforms:
    - name: Debian
      versions:
        - bookworm

  galaxy_tags:
    - postgresql
    - patroni
    - ha
    - database

dependencies: []
