---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Install iptables-persistent on Debian
  ansible.builtin.apt:
    name: iptables-persistent
    state: present
    update_cache: true
  when:
    - ansible_facts.os_family == "Debian"

- name: Stop and disable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false
  when:
    - ansible_facts.os_family == "RedHat"
    - "'firewalld.service' in ansible_facts.services"
