---
- name: Validate nginx configuration
  become: true
  ansible.builtin.command: nginx -t
  changed_when: false
  listen: Reload nginx

- name: Reload nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: reloaded
  listen: Reload nginx
