---
- name: Import cleanup tasks
  ansible.builtin.import_tasks: cleanup.yml
- name: Import install tasks
  ansible.builtin.import_tasks: install.yml
- name: Import build tasks
  ansible.builtin.import_tasks: build.yml
- name: Import run tasks
  ansible.builtin.import_tasks: run.yml
