---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install PostgreSQL packages
  ansible.builtin.apt:
    name: "{{ postgres_packages }}"
    state: present

- name: Create Ansible temporary directory for postgres user
  ansible.builtin.file:
    path: "{{ postgres_ansible_tmp_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: "0700"

- name: Ensure PostgreSQL service is enabled
  ansible.builtin.service:
    name: "{{ postgres_service }}"
    enabled: true
    state: started
