---
- name: Gather PostgreSQL cluster information
  ansible.builtin.command:
    cmd: pg_lsclusters --no-header
  register: postgres_cluster
  changed_when: false


- name: Verify PostgreSQL cluster is online
  ansible.builtin.assert:
    that:
      - "'online' in postgres_cluster.stdout"
    fail_msg: "PostgreSQL cluster is not running."
    success_msg: "PostgreSQL cluster is running."


- name: Show PostgreSQL cluster status
  ansible.builtin.debug:
    msg: "{{ postgres_cluster.stdout_lines }}"
