---
- name: Install BIND9 packages
  apt:
    name: "{{ bind_packages }}"
    state: present
    update_cache: true

- name: Enable and start BIND9
  service:
    name: "{{ bind_service }}"
    enabled: true
    state: started
