---
- name: Install BIND packages
  ansible.builtin.import_tasks: install.yml

- name: Configure BIND
  ansible.builtin.import_tasks: config.yml

- name: Configure DNS zones
  ansible.builtin.import_tasks: zones.yml
