---
gitlab_external_url: "http://gitlab.diego.home"
gitlab_registry_external_url: "http://gitlab.diego.home:5050"
gitlab_runner_name: "gitlab-diego-home-docker"
gitlab_runner_tags: "docker,linux"
# Оставьте пустым при первом запуске. После создания Runner раскомментируйте.
gitlab_runner_token: "glrt-rN4RSzN-Lcs_HS-gQTYIM286MQpwOjIKdDozCnU6Mw8.01.1717voo2m"
# gitlab_runner_token: "{{ vault_gitlab_runner_token }}"

# Заполните после создания проекта. ID можно взять в Settings -> General.
# gitlab_project_id: "123"
# gitlab_api_token: "{{ vault_gitlab_api_token }}"
# gitlab_cicd_variables:
#   - key: APP_SECRET
#     value: "{{ vault_application_secret }}"
#     masked: true
#     protected: true
