---
galaxy_info:
  role_name: docker
  author: DiegoGarsia
  description: Install Docker Engine on Debian
  license: MIT

  min_ansible_version: "2.16"

  platforms:
    - name: Debian
      versions:
        - all

dependencies: []
